/**
 * Created by artak on 2/15/17.
 */

export let events = {
  CLIENT_CONNECTED: 1,
  CLIENT_FAILURE: 2,
  CLIENT_STOP: 3,
  CLIENT_PING: 4,
  OPTIONS_SYNC: 5,
  SERVER_RECONNECT: 6,
  SERVER_FAILURE: 7,
  SERVER_STOP: 8,
  METRICS: 9,
  SERVER_RECONNECT_FAILURE: 10
}
